# Generated by Django 2.0 on 2017-12-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20171203_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birthdate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
