# Generated by Django 2.0 on 2017-12-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20171203_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='death_certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wedding_certificae',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wedding_place',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wedding_source_doc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
